apiVersion: 1
datasources:
  - name: AquaOS InfluxDB
    uid: aquaos-influxdb
    type: influxdb
    access: proxy
    url: ${AQUAOS_INFLUXDB_URL}
    jsonData:
      version: Flux
      organization: ${AQUAOS_INFLUXDB_ORG}
      defaultBucket: ${AQUAOS_INFLUXDB_BUCKET}
      tlsSkipVerify: false
    secureJsonData:
      token: ${AQUAOS_INFLUXDB_TOKEN}
