build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.23
labels:
  org.opencontainers.image.title: AquaOS Home Assistant app
  org.opencontainers.image.source: https://github.com/tylerkirby004-droid/AquaOS
